name: cpp11-exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-projects:latest
            options: -u root
        steps:
            - name: environment  
              run: |
                echo PWD $PWD
                id
                ls -al
                echo GH $GITHUB_WORKSPACE
                ls -al $GITHUB_WORKSPACE
            - name: checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: solutions   
                fetch-depth: 1               
            - name: build  
              run: |
                ls -al $GITHUB_WORKSPACE
                ls -l /home
                ls -l /home/feabhas
                cp -r /home/feabhas/projects/cmake-host .
                cd cmake-host
                bash ./build-one.sh --all                
