name: cpp11-exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-tdd:latest
            options: -u 1001
        steps:
            - name: environment  
              run: |
                echo PWD $PWD
                id
                ls -al
                echo $PATH
                type gcovr
            - name: checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: solutions
                fetch-depth: 1               
            # - name: build  
            #   run: |
            #     ls -al $GITHUB_WORKSPACE
            #     ls -l /home
            #     ls -l /home/feabhas
            #     cp -r /home/feabhas/projects/cmake-host .
            #     cd cmake-host
            #     bash ./build-one.sh --all                
            # - name: finish 
            #   run: |
            #     pwd
            #     ls -al $GITHUB_WORKSPACE
            #     ls -al
