name: cpp11-exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-projects:latest
            # credentials:
            #     username: ${{ secrets.DOCKER_HUB_USER }}
            #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
        steps:                      
            - name: check env  
              run: |
                echo PWD $PWD
                ls /home
                id
