name: cpp11-exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-projects:latest
            # credentials:
            #     username: ${{ secrets.DOCKER_HUB_USER }}
            #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
        steps:                      
            - name: build  
              run: |
                echo PWD $PWD
                echo DIR *
                echo GH ${{ github.workspace }}
                ls ${{ github.workspace }}
                cp -r ${{ github.workspace }}/solutions ~/workspace
                cd ~/workspace
                cp -r ~/projects/cmake-host .
                cd make-host
                bash ./build-one.sh --all                
